### ISSUE TITLE
间歇性的显示湿度和温度

### ISSUE THREAD

**Issue by Feeeeeelix** [nature2608/arduino-ESP8266-HomeKit#3]
在HomeKit里，显示十几秒或者几秒钟温湿度数值之后，温湿度读数会变成“0% 0.0°”这样大约几秒或者十几秒；之后又重新显示温湿度数值十几秒或者几秒钟，之后又变成“0% 0.0°”。感谢🙏大佬的固件～～

**Comment by nature2608** [comment]
应该是温湿度读取失败导致的，写了一版代码就再也没有测试过了，可以尝试改一下温湿度读取的代码。 @Feeeeeelix
